CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    role VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
)